In [22]:
import numpy as np
from keras.datasets import mnist
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, Flatten, Dropout
from keras.utils import to_categorical

In [23]:
(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

In [24]:
train_images.shape

(60000, 28, 28)

In [25]:
#Normalizing the pixels to [-0.5, 0.5]
train_images = (train_images/255) - 0.5
test_images = (test_images/255) - 0.5

#Flattening the images. i.e convert 28*28 into 784 dim vector to feed it to neural network
train_images = train_images.reshape((-1, 784))
test_images = test_images.reshape((-1, 784))

train_images.shape

(60000, 784)

In [26]:
# Building a model with 3 hidden layers. 2 with 64 neurons and 1 with 10 neurons (digits 0 - 9)
model = Sequential()

model.add(Dense(64, activation='relu', input_dim=784))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [27]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [28]:
# to_categorical changes the labels to no.of classes eg. 2 it expects [0,0,1,0,0,0,0,0,0,0] 
# epochs represents the no.of iterations
# batch_size represents no.of samples per gradient upgrade for training

model.fit(train_images, to_categorical(train_labels), epochs=10, batch_size=16)

Epoch 1/10
60000/60000 [==============================] - 11s 176us/step - loss: 0.3378 - accuracy: 0.8967
Epoch 2/10
60000/60000 [==============================] - 10s 173us/step - loss: 0.1766 - accuracy: 0.9461
Epoch 3/10
60000/60000 [==============================] - 10s 173us/step - loss: 0.1376 - accuracy: 0.9575
Epoch 4/10
60000/60000 [==============================] - 10s 174us/step - loss: 0.1195 - accuracy: 0.9624
Epoch 5/10
60000/60000 [==============================] - 11s 177us/step - loss: 0.1031 - accuracy: 0.9677
Epoch 6/10
60000/60000 [==============================] - 10s 172us/step - loss: 0.0949 - accuracy: 0.9706
Epoch 7/10
60000/60000 [==============================] - 10s 170us/step - loss: 0.0871 - accuracy: 0.9728
Epoch 8/10
60000/60000 [==============================] - 10s 170us/step - loss: 0.0802 - accuracy: 0.9742
Epoch 9/10
60000/60000 [==============================] - 10s 172us/step - loss: 0.0737 - accuracy: 0.9763
Epoch 10/10
60000/60000 [============

In [29]:
# Evaluate the model

model.evaluate(test_images, to_categorical(test_labels))

10000/10000 [==============================] - 0s 45us/step


[0.11603072364375694, 0.9674999713897705]

In [30]:
# Save neural network structure
# model_structure = model.to_json()
# f = Path("model_structure.json")
# f.write_text(model_structure)

# Save neural network's trained weights
# model.save_weights("model_weights.h5")

In [31]:
# predicting on the first 5 test_images
pred = model.predict(test_images[:5])
pred

array([[9.63695183e-12, 1.21519247e-06, 3.87382488e-06, 5.65588234e-05,
        8.60424731e-10, 3.87498105e-08, 3.19893697e-18, 9.99844790e-01,
        5.14938563e-07, 9.30122405e-05],
       [4.83501260e-12, 9.26130906e-06, 9.99990702e-01, 1.48268429e-08,
        2.38312002e-22, 3.01521401e-14, 4.40906235e-11, 3.89493169e-12,
        6.00284711e-09, 4.05846595e-22],
       [1.50405521e-10, 9.99997377e-01, 1.31885622e-08, 9.90379156e-09,
        5.64749541e-07, 5.91221749e-07, 1.04254860e-09, 1.14104739e-06,
        1.80806481e-07, 3.31427463e-09],
       [9.99996185e-01, 1.20795182e-12, 1.73506791e-07, 1.23642332e-08,
        4.39261988e-10, 1.29732340e-08, 3.34833271e-06, 1.05137827e-08,
        6.79029000e-10, 3.83891688e-07],
       [2.80064943e-10, 3.41399842e-09, 1.07929516e-07, 3.34813990e-08,
        9.99659300e-01, 8.42005011e-06, 1.04455244e-09, 3.00582201e-06,
        1.36775270e-06, 3.27870366e-04]], dtype=float32)

In [32]:
# print our model prediction
print(np.argmax(pred, axis=1))
print(test_labels[:5])

[7 2 1 0 4]
[7 2 1 0 4]
