In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from keras.datasets import cifar10
from keras.models import Sequential
from keras.utils import to_categorical
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D

In [29]:
(train_images, train_labels), (test_images, test_labels) = cifar10.load_data()

In [30]:
train_images.shape

(50000, 32, 32, 3)

In [31]:
#Normalizing the values from -0.5 to 0.5
train_images = (train_images/255) - 0.5
test_images = (test_images/255) - 0.5

#Reshaping the the input into 1d vector to feed the ANN model
# train_images = train_images.reshape((-1, 3072))
# test_images = test_images.reshape((-1, 3072))
train_images.shape

(50000, 32, 32, 3)

In [32]:
#Creating an ANN model
model = Sequential()

model.add(Conv2D(64, 3, padding='same', activation='relu', input_shape=(32,32,3)))
model.add(Conv2D(64, 3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Conv2D(32, 3, padding='same', activation='relu'))
model.add(Conv2D(32, 3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(10, activation='softmax'))

In [33]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [34]:
model.fit(train_images, to_categorical(train_labels), batch_size=32, epochs=5)

Epoch 1/5
50000/50000 [==============================] - 249s 5ms/step - loss: 1.4095 - accuracy: 0.4863
Epoch 2/5
50000/50000 [==============================] - 249s 5ms/step - loss: 1.0234 - accuracy: 0.6363
Epoch 3/5
50000/50000 [==============================] - 258s 5ms/step - loss: 0.8667 - accuracy: 0.6964
Epoch 4/5
50000/50000 [==============================] - 263s 5ms/step - loss: 0.7689 - accuracy: 0.7300
Epoch 5/5
50000/50000 [==============================] - 260s 5ms/step - loss: 0.7032 - accuracy: 0.7542


In [35]:
model.evaluate(test_images, to_categorical(test_labels))

10000/10000 [==============================] - 12s 1ms/step


[0.7037575604438782, 0.7556999921798706]

In [36]:
# predicting on the first 5 test_images
pred = model.predict(test_images[:5])
pred

array([[4.54087480e-04, 2.75177357e-04, 3.86929070e-03, 6.49791300e-01,
        8.62292771e-04, 2.46037602e-01, 9.64834020e-02, 1.01940683e-03,
        1.12377282e-03, 8.37714615e-05],
       [6.93973433e-03, 1.96889907e-01, 9.00694133e-08, 1.21194887e-06,
        4.66065853e-09, 9.77344539e-10, 1.84605646e-08, 1.04472129e-08,
        7.95780361e-01, 3.88665416e-04],
       [2.16798961e-01, 3.26107107e-02, 1.67577958e-03, 3.55984108e-03,
        1.74253073e-04, 3.59053884e-05, 1.35450609e-04, 1.17688265e-04,
        6.77874446e-01, 6.70169592e-02],
       [8.17942977e-01, 4.45813825e-03, 3.94708961e-02, 2.54621524e-02,
        1.27186463e-03, 1.33997749e-03, 1.77092245e-03, 2.97575491e-04,
        9.26724821e-02, 1.53131355e-02],
       [2.48985774e-08, 1.62697097e-06, 5.89259155e-03, 1.28253538e-03,
        9.00968760e-02, 2.54980023e-06, 9.02723730e-01, 1.50997614e-08,
        1.05522219e-07, 2.47664769e-08]], dtype=float32)

In [40]:
# print our model prediction
print(np.argmax(pred, axis=1))
print(test_labels[:5])

[3 8 8 0 6]
[[3]
 [8]
 [8]
 [0]
 [6]]


In [41]:
class_labels = [
    "Plane",
    "Car",
    "Bird",
    "Cat",
    "Deer",
    "Dog",
    "Frog",
    "Horse",
    "Boat",
    "Truck"
]

In [43]:
most_likely_class_index = int(np.argmax(pred[1]))
class_likelihood = pred[1][most_likely_class_index]

class_label = class_labels[most_likely_class_index]

print("This is image is a {} - Likelihood: {:2f}".format(class_label, class_likelihood))

This is image is a Boat - Likelihood: 0.795780
